Fix the entitlements team cache when there are multiple instances of GitHub in use.
github/entitlements-github-plugin pull request #30
Opened 2024-01-28 13:54 UTC by chrisgavin

I think currently the team cache gets confused when you have multiple GitHub Enterprise Server instances (or one Enterprise instance and DotCom) that have an organization and team with the same name.

To avoid this, I believe we need to include the base address of the instance as part of the cache structure. This ensures each instance has its own cache.

2024-01-28 14:18 UTC, chrisgavin commented
The acceptance tests are also failing on main in the same way, so I don't think they're related to the change.

2024-01-29 03:27 UTC, jasonmacgowan requested changes

2024-01-29 03:27 UTC, jasonmacgowan commented on lib/entitlements/backend/github_team/service.rb
> +          @team_cache = Entitlements.cache[:github_team_members][addr][org]
🎉 Thank you for this!

There is a method on the base GitHub service class use use to handle this collision for org membership, let's use that instead for consistency.

```suggestion
          Entitlements.cache[:github_team_members][org_signature] ||= {}
          @team_cache = Entitlements.cache[:github_team_members][org_signature]
```

2024-01-29 03:38 UTC, jasonmacgowan commented
https://github.com/github/entitlements-github-plugin/pull/32 should fix the acceptance test errors

2024-01-29 03:47 UTC, jasonmacgowan commented
@chrisgavin can you also bump the version so we can publish the gem when it merges :bow:

2024-01-29 08:59 UTC, jasonmacgowan approved these changes

2024-01-29 08:59 UTC, merged